export const arabic = {
  loadingtext: "صمم هذا التطبيق لحل مشكلتك فى وقت قصير وبأى وسائل ",
  welcometext: "أهلا بك !",
  logintext: "تسجيل الدخول ",
  logouttext: "تسجيل الخروج ",
  servicestitle: "خدماتنا",
  randomservices: "بعض الخدمات العشوائية ",
  orderstitle: "طلبات المستخدمين",
  btnordertext: "إكتب تفاصيل طلبك هنا ",
  btnpublishtext: "انشر",
  placeholderordertext: "أكتب تفاصيل طلبك هنا وفوراً بتجيك عروض المساعدة ",
  phonelogintext:
    " ادخل رقم جوالك لتسجيل الدخول / او لإئشاء حساب سريع وإكمال الييانات لاحقا",
  createaccounttext: "إنشاء حساب ",
  loginsuretext: "تأكيد الدخول ",
  hiddenphonechecktext: "تم ارسال رمز التحقق علي الرقم",
  writephonecodetext: "أدخل رمز التحقق",
  replaysendcodetext: "أعد ارسال رمز التحقق",
  selecttype: "قم بإختيار نوع العضوية",
  customertext: "عميل",
  vendortext: "فنى",
  signasgest: "تسجيل الدخول كضيف ",
  placeholdernametext: "اسم المستخدم",
  placeholdercitytext: "المدينة",
  placeholderphonetext: "رقم الجوال ",
  placeholderimagebankext: " صوره لمعلومات التحويل  البنكى ",
  placeholderaboutkext: " نبذة عنى (إختيارى)",
  placeholderexprincesskillstext: " الخبرات والمهارات  ",
  placeholderjobtext: " المهنة ",
  selectlocationtext: "تحديد الموقع ",
  guesttext: "تسجيل الدخول كضيف",
  typevendortext: "الجنس",
  typemaletext: "أنثى ",
  typefemaletext: "ذكر",
  servicecustomertext: "إذا واجهت أى مشكلة يمكنك الإتصال بالدعم الفنى ",
  profiletext: "الملف الشخصى ",
  callservicecustomertext: "الإتصال بالدعم ",
  orderscontroltext: "إدارة الطلبات ",
  basketcarttext: "سلة الطلبات ",
  valuetext: "الرصيد",
  addnewservicetext: "إضافة خدمة جديدة ",
  socialmediabannertext:
    "تابع الخصومات وساعدنا فى التطور بإقتراحات من وسائل التواصل",
  addimageorvidotext: "إضافة صور أو فيديو ",
  descinputimagetext: "لجذب العملاء أضف صور وفيديو لأعمالك السابقة لنفس الخدمة",
  descinputTitletext: "لتبرز خدمتك إجعل عنوانك واضح ومختصر",
  servicetitletext: "عنوان الخدمة ",
  servicedetailstext: "تفاصيل الخدمة ",
  pricetext: " السعر  ",
  descinputPricetext: "انقر  مرتين للتعديل ",
  extraSercicetext: "إضافة خدمة إضافية ",
  Fortext: "مقابل",
  addservicebtntext: "إضافة الخدمة ",
  placeholdersearchinputtext: "اكتب كلمات مفتاحية",
  descservicetext: "وصف الخدمة ",
  offerstext: "العروض المقدمة ",
  notifactionOKtext: "مبروك!تم قبول خدمتك :",
  notifactionNotOKtext: "عذرا!!!لم يتم قبول خدمتك :",
  sharenowtext: "يمكنك مشاركتها الأن ",
  resonNotOKtext: "لمعرفة السبب إضغط هنا ",
  personaldetails: "البيانات الشخصية ",
  nametext: "الإسم",
  locationtext: "الموقع",
  detailesvendor: "معلومات الفنى ",
  servicesavailabletext: "الخدمات المتوفرة ",
  ratingandwhatcastomerssaystext: "التقييمات وأراء العملاء ",
  recommedndedsercicestext: "إقتراحات لخدمات فنيين أخرين ",
  keywordstext: "كلمات مفتاحية ",
  proplemwithvendortext: "إذا واجهت اى مشكلة مع الفنى يمكنك التواصل مع ",
  addimagetext: "أدخل صورة شخصية مناسبة (إختيارى)",
  addimagevenndortext:
    "أدخل صورة شخصية مناسبة لإستخدامها أثناء عرض طلبات العملاء ",
  savechaanggestext: "حفظ التغييرات ",
  contactwithmetext: "تواصل معى",
  addserviicestext: "إضافة  خدمات إضاافية",
  totaltext: "الإجمالى",
  addtobasket: "إضافة  الى االسلة",
  addserviicetext: "إضافة خدمةإضافية",
  changessavedtext: "حفظ التعديلات",
  bestratingtext: "الأعلى تقييماً",
  paywithtext: "الدفع بواسطة",
  payssure: "تأكيد الدفع",
  ordersbaskettext: "سلة الطلبات",
  coubonstext: "كوبونات الخصم",
  sumarrypaytext: "ملخص الدفع ",
  totalsecndrytext: "المجموع الفرعى",
  delevirytext: "رسوم التوصيل",
  totalprice: "المبلغ الإجمالى",
  doservicetext: "تنفيذ الخدمة",
  ordersnumbertext: "عدد الطلبات ",
  addressessavedtext: "العنواين المحفوظة ",
  valueaccounttext: "رصيد الحساب",
  addtext: "أضف",
  totalvaluetext: "الرصيد الكلى",
};
